Repository karenkj9000/wannabe-reddit, pull requests merged in 2022-10, with the labels that each got.

#1 Create README.md
  README.md
Labels: documentation, hacktoberfest

#3 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#10 Update README.md
  README.md
Labels: hacktoberfest-accepted
